apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 940268234712.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 940268234712.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: a063edf0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
